### ISSUE TITLE
compile: data.table and := error

### ISSUE THREAD

**Issue by liza-wood** [govscienceuseR/citationExtract#1]
@tylerandrewscott  The citation_compile function, as it is written in the citation_compile.R file, works just fine went I save it to my global environment and run it locally. But when I use the function via the citationExtract package (which is the exact same code), I get the error and traceback pasted in. There is something about the use of the := in the piped through pblapply function that throws it, but only as a saved function in a package and not other times. I can't understand why. Any ideas?
<img width="987" alt="Screen Shot 2022-09-01 at 5 12 28 PM" src="https://user-images.githubusercontent.com/43861059/187962351-e83de18b-23a0-4a4a-ad7e-e9f0275e7024.png">

**Comment by tylerandrewscott** [comment]
@liza-wood first woah my bad this was 29 days ago, sorry. 2nd, I think it's perhaps taht data.table isn't imported? In any case, I just added a line to avoid the :=, that was probably too cute on my part.
